 PROCESSOR 16F887
    #include <p16f887.inc>

__CONFIG _CONFIG1, _HS_OSC & _WDT_OFF & _LVP_OFF & _MCLRE_ON & _PWRTE_ON
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
CBLOCK  0x190	    ;GENRAL VARIABLES
    COUNTER	    ;0x190 addr
    COUNTER_FLAG
   
    
ENDC
CBLOCK	0x70	;IENTERRUPT SAVE VARIABLES
    W_TEMP	    ;0x70
    S_TEMP	    ;0x71
    SECOND_DIGIT    ;0x72
    MINUTE_DIGIT    ;0x73
    HOUR_DIGIT	    ;0x74
    SEC_ONES	    ;0x75
    SEC_TENS	    ;0x76
    MIN_ONES	    ;0x77
    MIN_TENS	    ;0x78
    HOUR_ONES	    ;0x79
    HOUR_TENS	    ;0x7A
    TEMP_VAR	    ;0x7B
    LCD_ADDR	    ;0x7C
ENDC
;RESET_VECTOR
    org 0x00
    GOTO MAIN_INIT
;INTERRUPT_VECTOR
    org 0x04
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF S_TEMP
    
    BANKSEL PIR1
    BTFSC PIR1,0
    GOTO TIMER1_INC
    
    
    
    
    GOTO ISR_EXIT
    
TIMER1_INC:
    BCF PIR1,0
    BANKSEL COUNTER
    INCF COUNTER,F
    BSF COUNTER_FLAG,0
    GOTO ISR_EXIT
    

    

    
ISR_EXIT:
    SWAPF S_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE  
;MAIN_CODE
    org 0x50
MAIN_INIT:
    BANKSEL ANSEL
    CLRF ANSEL
    CLRF ANSELH
    
    BANKSEL TRISC
    BSF TRISC,3	    ;I2C SCL
    BSF TRISC,4	    ;I2C SDA
    
    BSF INTCON,7    ;GIE EN
    BSF INTCON,6    ;PEIE EN
    
    
    ;SETUP TIMER1
    BANKSEL PIE1
    BSF PIE1,0	    ;EN TMR1 OVF
    
    BANKSEL T1CON
    BSF T1CON,5	    ;PCS IS SET TO 8
    BSF T1CON,4
    BCF T1CON,1	    ;INTERNAL CLK 
    BSF T1CON,0	    ;TIM1 ON
    ;TIMER1 END
    
    ;I2C SETUP
    BANKSEL SSPCON
    BSF SSPCON,5
    BSF SSPCON,3    ;master mode clock = FOSC / (4 * (SSPADD+1))
    
    BANKSEL SSPADD
    MOVLW 49
    MOVWF SSPADD    ;based on this formula clock = FOSC / (4 * (SSPADD+1)) if we set SSPADD to 49 we get a 100khz clk for the i2c,
		    ;we also can overclock it more until 400khz but for only  LIQUID disp u dont need to dothat
    CLRF LCD_ADDR
    MOVLW 0x27	    ;addr of the lcd based on datasheet
    MOVWF LCD_ADDR
    ;I2C END		    
    GOTO MAIN_LOOP
    
MAIN_LOOP:
    BANKSEL COUNTER_FLAG
    BTFSC COUNTER_FLAG,0
    CALL COUNTER_LOGIC
    
    MOVF SECOND_DIGIT,W
    SUBLW 60
    BTFSC STATUS,2
    CALL SEC_MIN_INC
    
    MOVF MINUTE_DIGIT,W
    SUBLW 60
    BTFSC STATUS,2
    CALL MIN_HR_INC
    
   MOVF HOUR_DIGIT,W
    SUBLW 24
    BTFSC STATUS,2
    CALL HOUR_RESET
    CALL SPLIT
    
   
    GOTO MAIN_LOOP
    
COUNTER_LOGIC:
    BANKSEL COUNTER_FLAG
    CLRF COUNTER_FLAG
    MOVLW 10
    SUBWF COUNTER,W
    BTFSS STATUS,2
    RETURN
    CLRF COUNTER
    INCF SECOND_DIGIT,F
    RETURN

SEC_MIN_INC:
    CLRF SECOND_DIGIT
    INCF MINUTE_DIGIT,F
    RETURN
  
MIN_HR_INC:
    CLRF MINUTE_DIGIT
    INCF HOUR_DIGIT,F
    RETURN
    
HOUR_RESET:
    CLRF HOUR_DIGIT
    RETURN
    
SPLIT:
    ;SECONDS
    CLRF SEC_TENS
    MOVF SECOND_DIGIT,W
    MOVWF TEMP_VAR
SEC_LOOP:
    MOVLW d'10'
    SUBWF TEMP_VAR,F
    BTFSS STATUS,C
    GOTO SEC_DONE
    INCF SEC_TENS,F
    GOTO SEC_LOOP
SEC_DONE:
    MOVLW d'10'
    ADDWF TEMP_VAR,W
    MOVWF SEC_ONES

    ;MINUTES
    CLRF MIN_TENS
    MOVF MINUTE_DIGIT,W
    MOVWF TEMP_VAR
MIN_LOOP:
    MOVLW d'10'
    SUBWF TEMP_VAR,F
    BTFSS STATUS,C
    GOTO MIN_DONE
    INCF MIN_TENS,F
    GOTO MIN_LOOP
MIN_DONE:
    MOVLW d'10'
    ADDWF TEMP_VAR,W
    MOVWF MIN_ONES

    ;HOURS
    CLRF HOUR_TENS
    MOVF HOUR_DIGIT,W
    MOVWF TEMP_VAR
HOUR_LOOP:
    MOVLW d'10'
    SUBWF TEMP_VAR,F
    BTFSS STATUS,C
    GOTO HOUR_DONE
    INCF HOUR_TENS,F
    GOTO HOUR_LOOP
HOUR_DONE:
    MOVLW d'10'
    ADDWF TEMP_VAR,W
    MOVWF HOUR_ONES

    RETURN
    
I2C_START_:
    BANKSEL SSPCON2
    BSF SSPCON2,0	;START CONDITION
    
SEN_WAIT:		;so we will wait here until MSSP finishes whatever he is doing
    BTFSC SSPCON2,0
    GOTO SEN_WAIT
    
    RETURN
    
LCD_ADDR_SEND_WRITE:		;ts subroutine only sends the lcd addr
    BCF STATUS,0
    RLF LCD_ADDR,W	;we will shift the address then add 0 to the address then to the bus to write data
    
    BANKSEL SSPBUF
    MOVWF SSPBUF
    
    BANKSEL SSPSTAT
BUF_WAIT_WRITE:
    BTFSC SSPSTAT,2	;wait until the MSSP sends the data, then wait and check if we get ACK or NACK from the slave
    GOTO BUF_WAIT_WRITE
    CALL DELAY
    BANKSEL SSPCON2
    BTFSC SSPCON2,6
    GOTO I2C_ERROR
    RETURN
    
LCD_ADDR_SEND_READ:		;ts subroutine only sends the lcd addr
    BSF STATUS,0
    RLF LCD_ADDR,W	;we will shift the address then add 0 to the address then to the bus to write data
    
    BANKSEL SSPBUF
    MOVWF SSPBUF
    
    BANKSEL SSPSTAT
BUF_WAIT_READ:
    BTFSC SSPSTAT,2	;wait until the MSSP sends the data, then wait and check if we get ACK or NACK from the slave
    GOTO BUF_WAIT_READ
    CALL DELAY
    BANKSEL SSPCON2
    BTFSC SSPCON2,6
    GOTO I2C_ERROR
    RETURN
    
    
I2C_SEND_BYTE:
    BANKSEL SSPBUF
    MOVWF SSPBUF
    BANKSEL SSPSTAT
WAIT_BYTE:
    BTFSC SSPSTAT,2
    GOTO WAIT_BYTE
    CALL DELAY
    BANKSEL SSPCON2
    BTFSC SSPCON2,6
    GOTO I2C_ERROR
    RETURN
    
I2C_READ_BYTE_ACK:
    BANKSEL SSPCON2
    BSF SSPCON2,3	; Receive Enable bit (in I2C Master mode only)
    
WAIT_RCEN:
    BTFSC SSPCON,3
    GOTO WAIT_RCEN
    BANKSEL SSPBUF
    MOVF SSPBUF,W
    ;MOVWF TO SOME VARIABLE
    BANKSEL SSPCON2
    BCF SSPCON2,5	;SET IT TO 0 means when we recive data send an ACK
    BSF SSPCON2,4	;then pull the trigger and send the ACK, to the bus
    RETURN
    
I2C_READ_BYTE_NACK:
    BANKSEL SSPCON2
    BSF SSPCON2,3
WAIT_RCEN1:
    BTFSC SSPCON2,3
    GOTO WAIT_RCEN1
    BANKSEL SSPBUF
    MOVF SSPBUF,W
    ;MOVWF TO SOME VARIABLE
    BANKSEL SSPCON2
    BSF SSPCON2,5
    BSF SSPCON2,4
    RETURN
    
    
I2C_STOP_:
    BANKSEL SSPCON2
    BSF SSPCON2,2	;Stop Condition Enable bit (in I2C Master mode only)
    
WAIT_STOP:
    BTFSC SSPCON2,2
    GOTO WAIT_STOP
    RETURN
    
I2C_ERROR:
    ;NOTHING HERE YET
    RETURN

    
DELAY:
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    RETURN
END
