 PROCESSOR 16F887
    #include <p16f887.inc>

__CONFIG _CONFIG1, _HS_OSC & _WDT_OFF & _LVP_OFF & _MCLRE_ON & _PWRTE_ON
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
CBLOCK  0x190	    ;GENRAL VARIABLES
    COUNTER	    ;0x190 addr
    COUNTER_FLAG
    DISP_COUNTER
    DISP_BUF_0
    DISP_BUF_1
    DISP_BUF_2
    DISP_BUF_3
    DISP_BUF_4
    DISP_BUF_5
ENDC
CBLOCK	0x70	;IENTERRUPT SAVE VARIABLES
    W_TEMP	    ;0x70
    S_TEMP	    ;0x71
    SECOND_DIGIT    ;0x72
    MINUTE_DIGIT    ;0x73
    HOUR_DIGIT	    ;0x74
    SEC_ONES	    ;0x75
    SEC_TENS	    ;0x76
    MIN_ONES	    ;0x77
    MIN_TENS	    ;0x78
    HOUR_ONES	    ;0x79
    HOUR_TENS	    ;0x7A
ENDC
;RESET_VECTOR
    org 0x00
    GOTO MAIN_INIT
;INTERRUPT_VECTOR
    org 0x04
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF S_TEMP
    
    BANKSEL PIR1
    BCF PIR1,0
    BANKSEL COUNTER
    INCF COUNTER,F
    BSF COUNTER_FLAG,0
    
    ;EACH 1MS we will change what PORTD sends to the displays
    INCF DISP_COUNTER,F
    
    
    GOTO ISR_EXIT
    
ISR_EXIT:
    SWAPF S_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE  
;MAIN_CODE
    org 0x50
MAIN_INIT:
    BANKSEL ANSEL
    CLRF ANSEL
    CLRF ANSELH
    
    BANKSEL TRISD
    CLRF TRISD	    ;USED FOR DISPLAY SHOW
    CLRF TRISB	    ;USED FOR CONTROLLING THE DIGITS
    
    BSF INTCON,7    ;GIE EN
    BSF INTCON,6    ;PEIE EN
    
    
    ;SETUP TIMER1
    BANKSEL PIE1
    BSF PIE1,0	    ;EN TMR1 OVF
    
    BANKSEL T1CON
    BSF T1CON,5	    ;PCS IS SET TO 8
    BSF T1CON,4
    BCF T1CON,1	    ;INTERNAL CLK 
    BCF T1CON,0	    ;TIM1 OFF
    ;TIMER1 END
    
    ;TIMER0 SETUP
    BANKSEL OPTION_REG
    BCF OPTION_REG,5
    BCF OPTION_REG,3
    BSF OPTION_REG,2
    BCF OPTION_REG,1
    BCF OPTION_REG,0	    ;32 PCS so every 1.63 ms the timer0 will OVF and ISR will occurs
    
    BSF INTCON,5
    ;TIMER0 END
    GOTO MAIN_LOOP
    
MAIN_LOOP:
    BANKSEL COUNTER_FLAG
    BTFSC COUNTER_FLAG,0
    CALL COUNTER_LOGIC
    
    MOVF SECOND_DIGIT,W
    SUBLW 60
    BTFSC STATUS,2
    CALL SEC_MIN_INC
    
    MOVF MINUTE_DIGIT,W
    SUBLW 60
    BTFSC STATUS,2
    CALL MIN_HR_INC
    
   MOVF HOUR_DIGIT,W
    SUBLW 24
    BTFSC STATUS,2
    CALL HOUR_RESET
    CALL SPLIT
    GOTO MAIN_LOOP
    
COUNTER_LOGIC:
    BANKSEL COUNTER_FLAG
    CLRF COUNTER_FLAG
    MOVLW 10
    SUBWF COUNTER,W
    BTFSS STATUS,2
    GOTO COUNTER_LOGIC
    CLRF COUNTER
    INCF SECOND_DIGIT,F
    RETURN

SEC_MIN_INC:
    CLRF SECOND_DIGIT
    INCF MINUTE_DIGIT,F
    RETURN
  
MIN_HR_INC:
    CLRF MINUTE_DIGIT
    INCF HOUR_DIGIT,F
    RETURN
    
HOUR_RESET:
    CLRF HOUR_DIGIT
    RETURN
    
SPLIT:
    ;SECONDS
    CLRF SEC_TENS
    MOVF SECOND_DIGIT,W
    MOVWF W_TEMP
SEC_LOOP:
    MOVLW d'10'
    SUBWF W_TEMP,F
    BTFSS STATUS,C
    GOTO SEC_DONE
    INCF SEC_TENS,F
    GOTO SEC_LOOP
SEC_DONE:
    MOVLW d'10'
    ADDWF W_TEMP,W
    MOVWF SEC_ONES

    ;MINUTES
    CLRF MIN_TENS
    MOVF MINUTE_DIGIT,W
    MOVWF W_TEMP
MIN_LOOP:
    MOVLW d'10'
    SUBWF W_TEMP,F
    BTFSS STATUS,C
    GOTO MIN_DONE
    INCF MIN_TENS,F
    GOTO MIN_LOOP
MIN_DONE:
    MOVLW d'10'
    ADDWF W_TEMP,W
    MOVWF MIN_ONES

    ;HOURS
    CLRF HOUR_TENS
    MOVF HOUR_DIGIT,W
    MOVWF W_TEMP
HOUR_LOOP:
    MOVLW d'10'
    SUBWF W_TEMP,F
    BTFSS STATUS,C
    GOTO HOUR_DONE
    INCF HOUR_TENS,F
    GOTO HOUR_LOOP
HOUR_DONE:
    MOVLW d'10'
    ADDWF W_TEMP,W
    MOVWF HOUR_ONES

    RETURN
    
END
    





