 PROCESSOR 16F887
    #include <p16f887.inc>

__CONFIG _CONFIG1, _HS_OSC & _WDT_OFF & _LVP_OFF & _MCLRE_ON & _PWRTE_ON
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
CBLOCK  0x190	    ;GENRAL VARIABLES
    COUNTER	    ;0x190 addr
    COUNTER_FLAG
    SECOND_DIGIT    ;0x191 addr
    MINUTE_DIGIT
    HOUR_DIGIT
    
ENDC
CBLOCK	0x70	;IENTERRUPT SAVE VARIABLES
    W_TEMP	;0x70
    S_TEMP	;0x71
ENDC
;RESET_VECTOR
    org 0x00
    GOTO MAIN_INIT
;INTERRUPT_VECTOR
    org 0x04
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF S_TEMP
    
    BANKSEL PIR1
    BCF PIR1,0
    BANKSEL COUNTER
    INCF COUNTER,F
    BSF COUNTER_FLAG,0
    GOTO ISR_EXIT
    
ISR_EXIT:
    SWAPF S_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE  
;MAIN_CODE
    org 0x50
MAIN_INIT:
    BANKSEL ANSEL
    CLRF ANSEL
    CLRF ANSELH
    
    BANKSEL TRISD
    CLRF TRISD	    ;USED FOR DISPLAY SHOW
    CLRF TRISB	    ;USED FOR CONTROLLING THE DIGITS
    
    BSF INTCON,7    ;GIE EN
    BSF INTCON,6    ;PEIE EN
    
    
    ;SETUP TIMER1
    BANKSEL PIE1
    BSF PIE1,0	    ;EN TMR1 OVF
    
    BANKSEL T1CON
    BSF T1CON,5	    ;PCS IS SET TO 8
    BSF T1CON,4
    BCF T1CON,1	    ;INTERNAL CLK 
    BCF T1CON,0	    ;TIM1 OFF
    ;TIMER1 END
    
    GOTO MAIN_LOOP
    
MAIN_LOOP:
    BANKSEL COUNTER_FLAG
    BTFSC COUNTER_FLAG,0
    CALL COUNTER_LOGIC
    
    BANKSEL SECOND_DIGIT
    MOVF SECOND_DIGIT,W
    SUBLW 60
    BTFSS STATUS,2
    CALL SEC_MIN_INC
    
    BANKSEL MINUTE_DIGIT
    MOVF MINUTE_DIGIT,W
    SUBLW 60
    BTFSS STATUS,2
    CALL MIN_HR_INC
    
    BANKSEL HOUR_DIGIT
    MOVF HOUR_DIGIT,W
    SUBLW 24
    BTFSS STATUS,2
    CALL HOUR_RESET
    GOTO MAIN_LOOP
    
COUNTER_LOGIC:
    BANKSEL COUNTER_FLAG
    CLRF COUNTER_FLAG
    MOVLW 10
    SUBWF COUNTER,W
    BTFSS STATUS,2
    GOTO COUNTER_LOGIC
    CLRF COUNTER
    INCF SECOND_DIGIT,F
    RETURN

SEC_MIN_INC:
    BANKSEL SECOND_DIGIT
    CLRF SECOND_DIGIT
    INCF MINUTE_DIGIT,F
    RETURN
  
MIN_HR_INC:
    BANKSEL MINUTE_DIGIT
    CLRF MINUTE_DIGIT
    INCF HOUR_DIGIT,F
    RETURN
    
HOUR_RESET:
    BANKSEL HOUR_DIGIT
    CLRF HOUR_DIGIT
    RETURN
END
    





